/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BuySell {
  BUY, SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BuySell\",\"namespace\":\"gsp\",\"symbols\":[\"BUY\",\"SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
