/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Currency {
  USD, EUR, GBP, JPY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Currency\",\"namespace\":\"gsp\",\"symbols\":[\"USD\",\"EUR\",\"GBP\",\"JPY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
