/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CustomerAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2188443556666735635L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAccount\",\"namespace\":\"gsp\",\"fields\":[{\"name\":\"Mnemonic\",\"type\":\"string\"},{\"name\":\"GFCID\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerAccount> ENCODER =
      new BinaryMessageEncoder<CustomerAccount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerAccount> DECODER =
      new BinaryMessageDecoder<CustomerAccount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CustomerAccount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CustomerAccount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerAccount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CustomerAccount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CustomerAccount from a ByteBuffer. */
  public static CustomerAccount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Mnemonic;
  @Deprecated public java.lang.CharSequence GFCID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerAccount() {}

  /**
   * All-args constructor.
   * @param Mnemonic The new value for Mnemonic
   * @param GFCID The new value for GFCID
   */
  public CustomerAccount(java.lang.CharSequence Mnemonic, java.lang.CharSequence GFCID) {
    this.Mnemonic = Mnemonic;
    this.GFCID = GFCID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Mnemonic;
    case 1: return GFCID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Mnemonic = (java.lang.CharSequence)value$; break;
    case 1: GFCID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Mnemonic' field.
   * @return The value of the 'Mnemonic' field.
   */
  public java.lang.CharSequence getMnemonic() {
    return Mnemonic;
  }

  /**
   * Sets the value of the 'Mnemonic' field.
   * @param value the value to set.
   */
  public void setMnemonic(java.lang.CharSequence value) {
    this.Mnemonic = value;
  }

  /**
   * Gets the value of the 'GFCID' field.
   * @return The value of the 'GFCID' field.
   */
  public java.lang.CharSequence getGFCID() {
    return GFCID;
  }

  /**
   * Sets the value of the 'GFCID' field.
   * @param value the value to set.
   */
  public void setGFCID(java.lang.CharSequence value) {
    this.GFCID = value;
  }

  /**
   * Creates a new CustomerAccount RecordBuilder.
   * @return A new CustomerAccount RecordBuilder
   */
  public static gsp.CustomerAccount.Builder newBuilder() {
    return new gsp.CustomerAccount.Builder();
  }

  /**
   * Creates a new CustomerAccount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerAccount RecordBuilder
   */
  public static gsp.CustomerAccount.Builder newBuilder(gsp.CustomerAccount.Builder other) {
    return new gsp.CustomerAccount.Builder(other);
  }

  /**
   * Creates a new CustomerAccount RecordBuilder by copying an existing CustomerAccount instance.
   * @param other The existing instance to copy.
   * @return A new CustomerAccount RecordBuilder
   */
  public static gsp.CustomerAccount.Builder newBuilder(gsp.CustomerAccount other) {
    return new gsp.CustomerAccount.Builder(other);
  }

  /**
   * RecordBuilder for CustomerAccount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAccount>
    implements org.apache.avro.data.RecordBuilder<CustomerAccount> {

    private java.lang.CharSequence Mnemonic;
    private java.lang.CharSequence GFCID;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gsp.CustomerAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Mnemonic)) {
        this.Mnemonic = data().deepCopy(fields()[0].schema(), other.Mnemonic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.GFCID)) {
        this.GFCID = data().deepCopy(fields()[1].schema(), other.GFCID);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerAccount instance
     * @param other The existing instance to copy.
     */
    private Builder(gsp.CustomerAccount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Mnemonic)) {
        this.Mnemonic = data().deepCopy(fields()[0].schema(), other.Mnemonic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.GFCID)) {
        this.GFCID = data().deepCopy(fields()[1].schema(), other.GFCID);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Mnemonic' field.
      * @return The value.
      */
    public java.lang.CharSequence getMnemonic() {
      return Mnemonic;
    }

    /**
      * Sets the value of the 'Mnemonic' field.
      * @param value The value of 'Mnemonic'.
      * @return This builder.
      */
    public gsp.CustomerAccount.Builder setMnemonic(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Mnemonic = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Mnemonic' field has been set.
      * @return True if the 'Mnemonic' field has been set, false otherwise.
      */
    public boolean hasMnemonic() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Mnemonic' field.
      * @return This builder.
      */
    public gsp.CustomerAccount.Builder clearMnemonic() {
      Mnemonic = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'GFCID' field.
      * @return The value.
      */
    public java.lang.CharSequence getGFCID() {
      return GFCID;
    }

    /**
      * Sets the value of the 'GFCID' field.
      * @param value The value of 'GFCID'.
      * @return This builder.
      */
    public gsp.CustomerAccount.Builder setGFCID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.GFCID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'GFCID' field has been set.
      * @return True if the 'GFCID' field has been set, false otherwise.
      */
    public boolean hasGFCID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'GFCID' field.
      * @return This builder.
      */
    public gsp.CustomerAccount.Builder clearGFCID() {
      GFCID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerAccount build() {
      try {
        CustomerAccount record = new CustomerAccount();
        record.Mnemonic = fieldSetFlags()[0] ? this.Mnemonic : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.GFCID = fieldSetFlags()[1] ? this.GFCID : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerAccount>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAccount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerAccount>
    READER$ = (org.apache.avro.io.DatumReader<CustomerAccount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
