/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ECNName {
  MarketAxessNAM, MarketAxessEMEA  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ECNName\",\"namespace\":\"gsp\",\"symbols\":[\"MarketAxessNAM\",\"MarketAxessEMEA\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
