/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OfferingStack extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8218668551551992808L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OfferingStack\",\"namespace\":\"gsp\",\"fields\":[{\"name\":\"CUSIP\",\"type\":\"string\"},{\"name\":\"BuyPrices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Offering\",\"fields\":[{\"name\":\"CUSIP\",\"type\":\"string\"},{\"name\":\"Venue\",\"type\":\"string\"},{\"name\":\"Price\",\"type\":\"double\"},{\"name\":\"Size\",\"type\":\"double\"},{\"name\":\"Side\",\"type\":{\"type\":\"enum\",\"name\":\"BuySell\",\"symbols\":[\"BUY\",\"SELL\"]}}]}}},{\"name\":\"SellPrices\",\"type\":{\"type\":\"array\",\"items\":\"Offering\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OfferingStack> ENCODER =
      new BinaryMessageEncoder<OfferingStack>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OfferingStack> DECODER =
      new BinaryMessageDecoder<OfferingStack>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OfferingStack> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OfferingStack> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OfferingStack>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OfferingStack to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OfferingStack from a ByteBuffer. */
  public static OfferingStack fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence CUSIP;
  @Deprecated public java.util.List<gsp.Offering> BuyPrices;
  @Deprecated public java.util.List<gsp.Offering> SellPrices;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OfferingStack() {}

  /**
   * All-args constructor.
   * @param CUSIP The new value for CUSIP
   * @param BuyPrices The new value for BuyPrices
   * @param SellPrices The new value for SellPrices
   */
  public OfferingStack(java.lang.CharSequence CUSIP, java.util.List<gsp.Offering> BuyPrices, java.util.List<gsp.Offering> SellPrices) {
    this.CUSIP = CUSIP;
    this.BuyPrices = BuyPrices;
    this.SellPrices = SellPrices;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CUSIP;
    case 1: return BuyPrices;
    case 2: return SellPrices;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CUSIP = (java.lang.CharSequence)value$; break;
    case 1: BuyPrices = (java.util.List<gsp.Offering>)value$; break;
    case 2: SellPrices = (java.util.List<gsp.Offering>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CUSIP' field.
   * @return The value of the 'CUSIP' field.
   */
  public java.lang.CharSequence getCUSIP() {
    return CUSIP;
  }

  /**
   * Sets the value of the 'CUSIP' field.
   * @param value the value to set.
   */
  public void setCUSIP(java.lang.CharSequence value) {
    this.CUSIP = value;
  }

  /**
   * Gets the value of the 'BuyPrices' field.
   * @return The value of the 'BuyPrices' field.
   */
  public java.util.List<gsp.Offering> getBuyPrices() {
    return BuyPrices;
  }

  /**
   * Sets the value of the 'BuyPrices' field.
   * @param value the value to set.
   */
  public void setBuyPrices(java.util.List<gsp.Offering> value) {
    this.BuyPrices = value;
  }

  /**
   * Gets the value of the 'SellPrices' field.
   * @return The value of the 'SellPrices' field.
   */
  public java.util.List<gsp.Offering> getSellPrices() {
    return SellPrices;
  }

  /**
   * Sets the value of the 'SellPrices' field.
   * @param value the value to set.
   */
  public void setSellPrices(java.util.List<gsp.Offering> value) {
    this.SellPrices = value;
  }

  /**
   * Creates a new OfferingStack RecordBuilder.
   * @return A new OfferingStack RecordBuilder
   */
  public static gsp.OfferingStack.Builder newBuilder() {
    return new gsp.OfferingStack.Builder();
  }

  /**
   * Creates a new OfferingStack RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OfferingStack RecordBuilder
   */
  public static gsp.OfferingStack.Builder newBuilder(gsp.OfferingStack.Builder other) {
    return new gsp.OfferingStack.Builder(other);
  }

  /**
   * Creates a new OfferingStack RecordBuilder by copying an existing OfferingStack instance.
   * @param other The existing instance to copy.
   * @return A new OfferingStack RecordBuilder
   */
  public static gsp.OfferingStack.Builder newBuilder(gsp.OfferingStack other) {
    return new gsp.OfferingStack.Builder(other);
  }

  /**
   * RecordBuilder for OfferingStack instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OfferingStack>
    implements org.apache.avro.data.RecordBuilder<OfferingStack> {

    private java.lang.CharSequence CUSIP;
    private java.util.List<gsp.Offering> BuyPrices;
    private java.util.List<gsp.Offering> SellPrices;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gsp.OfferingStack.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CUSIP)) {
        this.CUSIP = data().deepCopy(fields()[0].schema(), other.CUSIP);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BuyPrices)) {
        this.BuyPrices = data().deepCopy(fields()[1].schema(), other.BuyPrices);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SellPrices)) {
        this.SellPrices = data().deepCopy(fields()[2].schema(), other.SellPrices);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OfferingStack instance
     * @param other The existing instance to copy.
     */
    private Builder(gsp.OfferingStack other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CUSIP)) {
        this.CUSIP = data().deepCopy(fields()[0].schema(), other.CUSIP);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BuyPrices)) {
        this.BuyPrices = data().deepCopy(fields()[1].schema(), other.BuyPrices);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SellPrices)) {
        this.SellPrices = data().deepCopy(fields()[2].schema(), other.SellPrices);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'CUSIP' field.
      * @return The value.
      */
    public java.lang.CharSequence getCUSIP() {
      return CUSIP;
    }

    /**
      * Sets the value of the 'CUSIP' field.
      * @param value The value of 'CUSIP'.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder setCUSIP(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CUSIP = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CUSIP' field has been set.
      * @return True if the 'CUSIP' field has been set, false otherwise.
      */
    public boolean hasCUSIP() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CUSIP' field.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder clearCUSIP() {
      CUSIP = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'BuyPrices' field.
      * @return The value.
      */
    public java.util.List<gsp.Offering> getBuyPrices() {
      return BuyPrices;
    }

    /**
      * Sets the value of the 'BuyPrices' field.
      * @param value The value of 'BuyPrices'.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder setBuyPrices(java.util.List<gsp.Offering> value) {
      validate(fields()[1], value);
      this.BuyPrices = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'BuyPrices' field has been set.
      * @return True if the 'BuyPrices' field has been set, false otherwise.
      */
    public boolean hasBuyPrices() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'BuyPrices' field.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder clearBuyPrices() {
      BuyPrices = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'SellPrices' field.
      * @return The value.
      */
    public java.util.List<gsp.Offering> getSellPrices() {
      return SellPrices;
    }

    /**
      * Sets the value of the 'SellPrices' field.
      * @param value The value of 'SellPrices'.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder setSellPrices(java.util.List<gsp.Offering> value) {
      validate(fields()[2], value);
      this.SellPrices = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'SellPrices' field has been set.
      * @return True if the 'SellPrices' field has been set, false otherwise.
      */
    public boolean hasSellPrices() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'SellPrices' field.
      * @return This builder.
      */
    public gsp.OfferingStack.Builder clearSellPrices() {
      SellPrices = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OfferingStack build() {
      try {
        OfferingStack record = new OfferingStack();
        record.CUSIP = fieldSetFlags()[0] ? this.CUSIP : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.BuyPrices = fieldSetFlags()[1] ? this.BuyPrices : (java.util.List<gsp.Offering>) defaultValue(fields()[1]);
        record.SellPrices = fieldSetFlags()[2] ? this.SellPrices : (java.util.List<gsp.Offering>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OfferingStack>
    WRITER$ = (org.apache.avro.io.DatumWriter<OfferingStack>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OfferingStack>
    READER$ = (org.apache.avro.io.DatumReader<OfferingStack>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
