/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RFQ extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1179085698204102611L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RFQ\",\"namespace\":\"gsp\",\"fields\":[{\"name\":\"ECNRFQId\",\"type\":\"string\"},{\"name\":\"Quantity\",\"type\":\"double\"},{\"name\":\"CUSIP\",\"type\":\"string\"},{\"name\":\"ECN\",\"type\":{\"type\":\"enum\",\"name\":\"ECNName\",\"symbols\":[\"MarketAxessNAM\",\"MarketAxessEMEA\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RFQ> ENCODER =
      new BinaryMessageEncoder<RFQ>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RFQ> DECODER =
      new BinaryMessageDecoder<RFQ>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RFQ> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RFQ> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RFQ>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RFQ to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RFQ from a ByteBuffer. */
  public static RFQ fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence ECNRFQId;
  @Deprecated public double Quantity;
  @Deprecated public java.lang.CharSequence CUSIP;
  @Deprecated public gsp.ECNName ECN;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RFQ() {}

  /**
   * All-args constructor.
   * @param ECNRFQId The new value for ECNRFQId
   * @param Quantity The new value for Quantity
   * @param CUSIP The new value for CUSIP
   * @param ECN The new value for ECN
   */
  public RFQ(java.lang.CharSequence ECNRFQId, java.lang.Double Quantity, java.lang.CharSequence CUSIP, gsp.ECNName ECN) {
    this.ECNRFQId = ECNRFQId;
    this.Quantity = Quantity;
    this.CUSIP = CUSIP;
    this.ECN = ECN;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ECNRFQId;
    case 1: return Quantity;
    case 2: return CUSIP;
    case 3: return ECN;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ECNRFQId = (java.lang.CharSequence)value$; break;
    case 1: Quantity = (java.lang.Double)value$; break;
    case 2: CUSIP = (java.lang.CharSequence)value$; break;
    case 3: ECN = (gsp.ECNName)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ECNRFQId' field.
   * @return The value of the 'ECNRFQId' field.
   */
  public java.lang.CharSequence getECNRFQId() {
    return ECNRFQId;
  }

  /**
   * Sets the value of the 'ECNRFQId' field.
   * @param value the value to set.
   */
  public void setECNRFQId(java.lang.CharSequence value) {
    this.ECNRFQId = value;
  }

  /**
   * Gets the value of the 'Quantity' field.
   * @return The value of the 'Quantity' field.
   */
  public java.lang.Double getQuantity() {
    return Quantity;
  }

  /**
   * Sets the value of the 'Quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Double value) {
    this.Quantity = value;
  }

  /**
   * Gets the value of the 'CUSIP' field.
   * @return The value of the 'CUSIP' field.
   */
  public java.lang.CharSequence getCUSIP() {
    return CUSIP;
  }

  /**
   * Sets the value of the 'CUSIP' field.
   * @param value the value to set.
   */
  public void setCUSIP(java.lang.CharSequence value) {
    this.CUSIP = value;
  }

  /**
   * Gets the value of the 'ECN' field.
   * @return The value of the 'ECN' field.
   */
  public gsp.ECNName getECN() {
    return ECN;
  }

  /**
   * Sets the value of the 'ECN' field.
   * @param value the value to set.
   */
  public void setECN(gsp.ECNName value) {
    this.ECN = value;
  }

  /**
   * Creates a new RFQ RecordBuilder.
   * @return A new RFQ RecordBuilder
   */
  public static gsp.RFQ.Builder newBuilder() {
    return new gsp.RFQ.Builder();
  }

  /**
   * Creates a new RFQ RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RFQ RecordBuilder
   */
  public static gsp.RFQ.Builder newBuilder(gsp.RFQ.Builder other) {
    return new gsp.RFQ.Builder(other);
  }

  /**
   * Creates a new RFQ RecordBuilder by copying an existing RFQ instance.
   * @param other The existing instance to copy.
   * @return A new RFQ RecordBuilder
   */
  public static gsp.RFQ.Builder newBuilder(gsp.RFQ other) {
    return new gsp.RFQ.Builder(other);
  }

  /**
   * RecordBuilder for RFQ instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RFQ>
    implements org.apache.avro.data.RecordBuilder<RFQ> {

    private java.lang.CharSequence ECNRFQId;
    private double Quantity;
    private java.lang.CharSequence CUSIP;
    private gsp.ECNName ECN;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gsp.RFQ.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ECNRFQId)) {
        this.ECNRFQId = data().deepCopy(fields()[0].schema(), other.ECNRFQId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[1].schema(), other.Quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CUSIP)) {
        this.CUSIP = data().deepCopy(fields()[2].schema(), other.CUSIP);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ECN)) {
        this.ECN = data().deepCopy(fields()[3].schema(), other.ECN);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RFQ instance
     * @param other The existing instance to copy.
     */
    private Builder(gsp.RFQ other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ECNRFQId)) {
        this.ECNRFQId = data().deepCopy(fields()[0].schema(), other.ECNRFQId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Quantity)) {
        this.Quantity = data().deepCopy(fields()[1].schema(), other.Quantity);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CUSIP)) {
        this.CUSIP = data().deepCopy(fields()[2].schema(), other.CUSIP);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ECN)) {
        this.ECN = data().deepCopy(fields()[3].schema(), other.ECN);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'ECNRFQId' field.
      * @return The value.
      */
    public java.lang.CharSequence getECNRFQId() {
      return ECNRFQId;
    }

    /**
      * Sets the value of the 'ECNRFQId' field.
      * @param value The value of 'ECNRFQId'.
      * @return This builder.
      */
    public gsp.RFQ.Builder setECNRFQId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ECNRFQId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ECNRFQId' field has been set.
      * @return True if the 'ECNRFQId' field has been set, false otherwise.
      */
    public boolean hasECNRFQId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ECNRFQId' field.
      * @return This builder.
      */
    public gsp.RFQ.Builder clearECNRFQId() {
      ECNRFQId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Quantity' field.
      * @return The value.
      */
    public java.lang.Double getQuantity() {
      return Quantity;
    }

    /**
      * Sets the value of the 'Quantity' field.
      * @param value The value of 'Quantity'.
      * @return This builder.
      */
    public gsp.RFQ.Builder setQuantity(double value) {
      validate(fields()[1], value);
      this.Quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Quantity' field has been set.
      * @return True if the 'Quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Quantity' field.
      * @return This builder.
      */
    public gsp.RFQ.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'CUSIP' field.
      * @return The value.
      */
    public java.lang.CharSequence getCUSIP() {
      return CUSIP;
    }

    /**
      * Sets the value of the 'CUSIP' field.
      * @param value The value of 'CUSIP'.
      * @return This builder.
      */
    public gsp.RFQ.Builder setCUSIP(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.CUSIP = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'CUSIP' field has been set.
      * @return True if the 'CUSIP' field has been set, false otherwise.
      */
    public boolean hasCUSIP() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'CUSIP' field.
      * @return This builder.
      */
    public gsp.RFQ.Builder clearCUSIP() {
      CUSIP = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ECN' field.
      * @return The value.
      */
    public gsp.ECNName getECN() {
      return ECN;
    }

    /**
      * Sets the value of the 'ECN' field.
      * @param value The value of 'ECN'.
      * @return This builder.
      */
    public gsp.RFQ.Builder setECN(gsp.ECNName value) {
      validate(fields()[3], value);
      this.ECN = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ECN' field has been set.
      * @return True if the 'ECN' field has been set, false otherwise.
      */
    public boolean hasECN() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ECN' field.
      * @return This builder.
      */
    public gsp.RFQ.Builder clearECN() {
      ECN = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RFQ build() {
      try {
        RFQ record = new RFQ();
        record.ECNRFQId = fieldSetFlags()[0] ? this.ECNRFQId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Quantity = fieldSetFlags()[1] ? this.Quantity : (java.lang.Double) defaultValue(fields()[1]);
        record.CUSIP = fieldSetFlags()[2] ? this.CUSIP : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ECN = fieldSetFlags()[3] ? this.ECN : (gsp.ECNName) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RFQ>
    WRITER$ = (org.apache.avro.io.DatumWriter<RFQ>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RFQ>
    READER$ = (org.apache.avro.io.DatumReader<RFQ>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
