/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gsp;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RiskAmount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4502520493534163963L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RiskAmount\",\"namespace\":\"gsp\",\"fields\":[{\"name\":\"Currency\",\"type\":{\"type\":\"enum\",\"name\":\"Currency\",\"symbols\":[\"USD\",\"EUR\",\"GBP\",\"JPY\"]}},{\"name\":\"Amount\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RiskAmount> ENCODER =
      new BinaryMessageEncoder<RiskAmount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RiskAmount> DECODER =
      new BinaryMessageDecoder<RiskAmount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RiskAmount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RiskAmount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RiskAmount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RiskAmount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RiskAmount from a ByteBuffer. */
  public static RiskAmount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public gsp.Currency Currency;
  @Deprecated public double Amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RiskAmount() {}

  /**
   * All-args constructor.
   * @param Currency The new value for Currency
   * @param Amount The new value for Amount
   */
  public RiskAmount(gsp.Currency Currency, java.lang.Double Amount) {
    this.Currency = Currency;
    this.Amount = Amount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Currency;
    case 1: return Amount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Currency = (gsp.Currency)value$; break;
    case 1: Amount = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Currency' field.
   * @return The value of the 'Currency' field.
   */
  public gsp.Currency getCurrency() {
    return Currency;
  }

  /**
   * Sets the value of the 'Currency' field.
   * @param value the value to set.
   */
  public void setCurrency(gsp.Currency value) {
    this.Currency = value;
  }

  /**
   * Gets the value of the 'Amount' field.
   * @return The value of the 'Amount' field.
   */
  public java.lang.Double getAmount() {
    return Amount;
  }

  /**
   * Sets the value of the 'Amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.Double value) {
    this.Amount = value;
  }

  /**
   * Creates a new RiskAmount RecordBuilder.
   * @return A new RiskAmount RecordBuilder
   */
  public static gsp.RiskAmount.Builder newBuilder() {
    return new gsp.RiskAmount.Builder();
  }

  /**
   * Creates a new RiskAmount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RiskAmount RecordBuilder
   */
  public static gsp.RiskAmount.Builder newBuilder(gsp.RiskAmount.Builder other) {
    return new gsp.RiskAmount.Builder(other);
  }

  /**
   * Creates a new RiskAmount RecordBuilder by copying an existing RiskAmount instance.
   * @param other The existing instance to copy.
   * @return A new RiskAmount RecordBuilder
   */
  public static gsp.RiskAmount.Builder newBuilder(gsp.RiskAmount other) {
    return new gsp.RiskAmount.Builder(other);
  }

  /**
   * RecordBuilder for RiskAmount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RiskAmount>
    implements org.apache.avro.data.RecordBuilder<RiskAmount> {

    private gsp.Currency Currency;
    private double Amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gsp.RiskAmount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Currency)) {
        this.Currency = data().deepCopy(fields()[0].schema(), other.Currency);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Amount)) {
        this.Amount = data().deepCopy(fields()[1].schema(), other.Amount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RiskAmount instance
     * @param other The existing instance to copy.
     */
    private Builder(gsp.RiskAmount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Currency)) {
        this.Currency = data().deepCopy(fields()[0].schema(), other.Currency);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Amount)) {
        this.Amount = data().deepCopy(fields()[1].schema(), other.Amount);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'Currency' field.
      * @return The value.
      */
    public gsp.Currency getCurrency() {
      return Currency;
    }

    /**
      * Sets the value of the 'Currency' field.
      * @param value The value of 'Currency'.
      * @return This builder.
      */
    public gsp.RiskAmount.Builder setCurrency(gsp.Currency value) {
      validate(fields()[0], value);
      this.Currency = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Currency' field has been set.
      * @return True if the 'Currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Currency' field.
      * @return This builder.
      */
    public gsp.RiskAmount.Builder clearCurrency() {
      Currency = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Amount' field.
      * @return The value.
      */
    public java.lang.Double getAmount() {
      return Amount;
    }

    /**
      * Sets the value of the 'Amount' field.
      * @param value The value of 'Amount'.
      * @return This builder.
      */
    public gsp.RiskAmount.Builder setAmount(double value) {
      validate(fields()[1], value);
      this.Amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Amount' field has been set.
      * @return True if the 'Amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Amount' field.
      * @return This builder.
      */
    public gsp.RiskAmount.Builder clearAmount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RiskAmount build() {
      try {
        RiskAmount record = new RiskAmount();
        record.Currency = fieldSetFlags()[0] ? this.Currency : (gsp.Currency) defaultValue(fields()[0]);
        record.Amount = fieldSetFlags()[1] ? this.Amount : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RiskAmount>
    WRITER$ = (org.apache.avro.io.DatumWriter<RiskAmount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RiskAmount>
    READER$ = (org.apache.avro.io.DatumReader<RiskAmount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
